version: "3"
services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: vrecipes
            POSTGRES_DB: vrecipes
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
        # command: -d 5

    adminer:
        image: adminer
        ports:
            - 8080:8080

    frontend-new:
        image: vrecipes_frontend_new_dev
        build:
            context: nextjs-frontend
            dockerfile: dev.Dockerfile
        ports:
            - 3000:3000
        volumes:
            - ./nextjs-frontend:/app
        environment:
            - DEBUG_MODE=true
        extra_hosts:
            host.docker.internal: host-gateway

    # frontend:
    #     image: vrecipes_frontend_dev
    #     build:
    #         context: ./frontend/
    #         dockerfile: dev.Dockerfile
    #     ports:
    #         - 3000:3000
    #     volumes:
    #         - ./frontend:/usr/src/vrecipes/frontend
    #     environment:
    #         - DEBUG_MODE=true
    #     extra_hosts:
    #         host.docker.internal: host-gateway
