version: "2"
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: vrecipes
            POSTGRES_DB: vrecipes
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
        # command: -d 5

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    frontend:
        image: vrecipes_frontend_dev
        build:
            context: ./frontend/
            dockerfile: dev.Dockerfile
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/usr/src/vrecipes/frontend
        environment:
            - DEBUG_MODE=true
