DROP TABLE IF EXISTS recipe_image;
DROP TABLE IF EXISTS image;

DROP TABLE IF EXISTS recipe_ingredient;
DROP TABLE IF EXISTS ingredient;
DROP TABLE IF EXISTS unit;

DROP TABLE IF EXISTS recipe_step;

DROP TABLE IF EXISTS recipe;

DROP TABLE IF EXISTS "user";
